services:
  hugo-website:
    image: testing-website-image
    environment:
      HUGO_FLAGS: "--bind=0.0.0.0"
      DOCFORGE_CONFIG: /run/secrets/docforge_config
    ports:
    - 1313:1313
    secrets:
    - docforge_config
secrets:
  docforge_config:
    file: ./docforge_config.yaml