#!/usr/bin/env bash

SOURCE_PATH="$(readlink -f "$(dirname ${0})/..")"
GARDENER_DOCUMENTATION_VERSION_PATH="$SOURCE_PATH/latestDocVersion"

${ADD_DEPENDENCIES_CMD} \
    --component-dependencies \
    '{"name": "github.com/swilen-iwanow/documentation", "version": "'$(cat $GARDENER_DOCUMENTATION_VERSION_PATH)'"}'

cp "${BASE_DEFINITION_PATH}" "${COMPONENT_DESCRIPTOR_PATH}"
