#!/usr/bin/env bash

sourceFilePath="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
filePath=$sourceFilePath/../latestDocVersion
versions=$(cat $filePath)

if [[ -f $filePath ]]; then
    echo ${DEPENDENCY_VERSION} >$sourceFilePath/../latestDocVersion && exit 0
fi

semver=(${DEPENDENCY_VERSION//./ })
depVersionMajor=(${semver[0]//[!0-9]/ }) # without v prefix: "v1" -> "1"
depVersionMinor=${semver[1]}
depVersionPatch=${semver[2]}

versionsSet=(${versions// /})
latestVersionSemVer=(${versionsSet[0]//./ })
latestVersionMajor=(${latestVersionSemVer[0]//v/ })
latestVersionMinor=${latestVersionSemVer[1]}

echo Current latest major version is $latestVersionMajor
echo Current latest minor version is $latestVersionMinor

if [[ $depVersionMajor -gt $latestVersionMajor || $depVersionMinor -gt $latestVersionMinor ]]; then
    result=${DEPENDENCY_VERSION}
    for i in $versions; do
        result="${result}\n${i}"
    done
    echo -e $result >latestDocVersions
    echo successfully updated documentation versions && exit 0
fi

f=${semver[0]}.${semver[1]}
substitude="s/\(^${f}.*$\)/${DEPENDENCY_VERSION}/g"
sed -i $substitude latestDocVersions
