#!/usr/bin/env bash

set -ex

HOST=europe-docker.pkg.dev
PROJECT=gardener-project
REPOSITORY=releases
IMAGE=gardener-website-generator
for i in "$@"
do
case $i in
  --t=*|--tag=*) 
    TAG="${i#*=}"
    shift
    ;;
  *) echo "Unknown parameter passed: $i"; exit 1;;
esac
done
if [[ -z "${TAG}" ]]; then
  echo "No image tag specified. Either use the --tag=your-tag option (-t=your-tag), or $TAG environment variable to specify it. The -t | --tag option has priority."
  exit 1;
fi

IMAGE="${HOST}/${PROJECT}/${REPOSITORY}/${IMAGE}"
foundImage=$(docker images "${IMAGE}:${TAG}" | tail -n +2)
if [[ -z "${foundImage}" ]]; then
  echo "Pulling locally image ${IMAGE}:${TAG}"
  docker pull "${IMAGE}:${TAG}"
fi

echo "Tagging image with tag ${TAG} as stable"
docker tag "${IMAGE}:${TAG}" "${IMAGE}:stable"

echo "Pushing image to GAR. Tagged as :stable"
docker push "${IMAGE}:stable"
