#!/usr/bin/env bash

set -ex

# GCR coordinates
HOST=eu.gcr.io
PROJECT=gardener-project
IMAGE=gardener-website-generator

for i in "$@"
do
case $i in
  --t=*|tag=*) 
    TAG="${i#*=}"
    shift
    ;;
  *) echo "Unknown parameter passed: $i"; exit 1;;
esac; shift; done
if [[ -z "${TAG}" ]]; then
  echo "No image tag specified. Either use the --tag=your-tag option (-t=your-tag), or $TAG environment variable to specify it. The -t | --tag option has priority."
  exit 1;
fi

# TODO: find out how can we do this with gcloud
# get latest version from the Docker registry and increment them
# VERSION=$(curl https://registry.hub.docker.com/v1/repositories/$REPOSITORY/$PROJECT/tags  | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}' | grep v| tail -n 1)
# VERSION=${VERSION:1}
# ((VERSION++))
# VERSION="v$VERSION"
# echo $VERSION

if [[ $(uname) == 'Darwin' ]]; then
  READLINK_BIN="greadlink"
else
  READLINK_BIN="readlink"
fi

ctxpath="$(${READLINK_BIN} -f "$(dirname "${0}")/..")"

echo "Building $HOST/$PROJECT/$IMAGE tagged as :$TAG and :latest"
docker build --no-cache=true -t "$HOST/$PROJECT/$IMAGE:$TAG" -t "$HOST/$PROJECT/$IMAGE:latest" "$ctxpath" | tee /tmp/docker_build_result.log
